import type { PluginManifest } from '../../../../shared/plugin-types';

const CLOCK_ICON = `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>`;

export const manifest: PluginManifest = {
  id: 'automations',
  name: 'Automations',
  version: '0.1.0',
  description: 'Schedule recurring quick-agent tasks with cron expressions.',
  author: 'Clubhouse',
  engine: { api: 0.4 },
  scope: 'project',
  contributes: {
    tab: { label: 'Automations', icon: CLOCK_ICON, layout: 'full' },
    commands: [{ id: 'create', title: 'Create Automation' }],
    help: {
      topics: [
        {
          id: 'automations',
          title: 'Automations',
          content: [
            '## Automations',
            '',
            'Schedule recurring quick-agent tasks using cron expressions.',
            '',
            '### Creating an automation',
            'Use the **Create Automation** command or click the **+** button. Provide a name, prompt, and cron schedule.',
            '',
            '### Managing automations',
            'The list view shows all automations for the current project. Click an automation to edit its settings.',
            '',
            '### Toggling',
            'Enable or disable an automation with the toggle switch. Disabled automations keep their schedule but will not run.',
            '',
            '### Run history',
            'Each automation tracks its recent runs with status (success/failure) and timestamps.',
          ].join('\n'),
        },
        {
          id: 'cron-schedules',
          title: 'Cron Schedules',
          content: [
            '## Cron Schedules',
            '',
            'Automations use standard 5-field cron expressions: `minute hour day-of-month month day-of-week`.',
            '',
            '### Presets',
            '| Preset | Expression | Description |',
            '|--------|-----------|-------------|',
            '| Every 15 minutes | `*/15 * * * *` | Runs at :00, :15, :30, :45 |',
            '| Hourly | `0 * * * *` | Runs at the top of every hour |',
            '| Daily at midnight | `0 0 * * *` | Runs once per day at 00:00 |',
            '| Weekly on Monday | `0 0 * * 1` | Runs at midnight every Monday |',
            '| Monthly | `0 0 1 * *` | Runs at midnight on the 1st |',
            '',
            '### Syntax reference',
            '- `*` — every value',
            '- `*/N` — every N units',
            '- `N` — specific value',
            '- `N,M` — list of values',
            '- `N-M` — range of values',
            '',
            '### Day-of-week values',
            '`0` = Sunday, `1` = Monday, `2` = Tuesday, `3` = Wednesday, `4` = Thursday, `5` = Friday, `6` = Saturday.',
            '',
            '### How scheduling works',
            'Schedules are evaluated locally on your machine. The automation will only run when Clubhouse is open and the project is active.',
          ].join('\n'),
        },
      ],
    },
  },
};
