import { ThemeDefinition } from '../../shared/types';

export const catppuccinLatte: ThemeDefinition = {
  id: 'catppuccin-latte',
  name: 'Catppuccin Latte',
  type: 'light',
  colors: {
    base: '#eff1f5',
    mantle: '#e6e9ef',
    crust: '#dce0e8',
    text: '#4c4f69',
    subtext0: '#6c6f85',
    subtext1: '#5c5f77',
    surface0: '#ccd0da',
    surface1: '#bcc0cc',
    surface2: '#acb0be',
    accent: '#1e66f5',
    link: '#1e66f5',
  },
  hljs: {
    keyword: '#8839ef',
    string: '#40a02b',
    number: '#fe640b',
    comment: '#9ca0b0',
    function: '#1e66f5',
    type: '#df8e1d',
    variable: '#d20f39',
    regexp: '#ea76cb',
    tag: '#1e66f5',
    attribute: '#df8e1d',
    symbol: '#d20f39',
    meta: '#fe640b',
    addition: '#40a02b',
    deletion: '#d20f39',
    property: '#179299',
    punctuation: '#7c7f93',
  },
  monaco: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: '', foreground: '4c4f69' },
      { token: 'invalid', foreground: 'd20f39' },
      { token: 'keyword', foreground: '8839ef' },
      { token: 'keyword.control', foreground: '8839ef' },
      { token: 'keyword.operator', foreground: '179299' },
      { token: 'storage', foreground: '8839ef' },
      { token: 'storage.type', foreground: '8839ef' },
      { token: 'string', foreground: '40a02b' },
      { token: 'string.escape', foreground: 'ea76cb' },
      { token: 'string.regexp', foreground: 'ea76cb' },
      { token: 'number', foreground: 'fe640b' },
      { token: 'number.hex', foreground: 'fe640b' },
      { token: 'constant', foreground: 'fe640b' },
      { token: 'comment', foreground: '9ca0b0', fontStyle: 'italic' },
      { token: 'entity.name.function', foreground: '1e66f5' },
      { token: 'support.function', foreground: '1e66f5' },
      { token: 'meta.function-call', foreground: '1e66f5' },
      { token: 'entity.name.type', foreground: 'df8e1d' },
      { token: 'entity.name.class', foreground: 'df8e1d' },
      { token: 'support.type', foreground: 'df8e1d' },
      { token: 'support.class', foreground: 'df8e1d' },
      { token: 'type', foreground: 'df8e1d' },
      { token: 'type.identifier', foreground: 'df8e1d' },
      { token: 'variable', foreground: '4c4f69' },
      { token: 'variable.parameter', foreground: 'd20f39' },
      { token: 'variable.other', foreground: '4c4f69' },
      { token: 'variable.property', foreground: '179299' },
      { token: 'support.variable.property', foreground: '179299' },
      { token: 'tag', foreground: '1e66f5' },
      { token: 'meta.tag', foreground: '1e66f5' },
      { token: 'attribute.name', foreground: 'df8e1d' },
      { token: 'attribute.value', foreground: '40a02b' },
      { token: 'inserted', foreground: '40a02b' },
      { token: 'deleted', foreground: 'd20f39' },
      { token: 'delimiter', foreground: '7c7f93' },
      { token: 'delimiter.bracket', foreground: '7c7f93' },
      { token: 'punctuation', foreground: '7c7f93' },
      { token: 'operator', foreground: '179299' },
      { token: 'string.key.json', foreground: '1e66f5' },
      { token: 'string.value.json', foreground: '40a02b' },
      { token: 'type.yaml', foreground: '1e66f5' },
      { token: 'markup.heading', foreground: '1e66f5', fontStyle: 'bold' },
      { token: 'markup.bold', fontStyle: 'bold' },
      { token: 'markup.italic', fontStyle: 'italic' },
      { token: 'markup.inline', foreground: 'd20f39' },
      { token: 'markup.underline.link', foreground: '1e66f5' },
    ],
    colors: {
      'editor.background': '#eff1f5',
      'editor.foreground': '#4c4f69',
      'editor.lineHighlightBackground': '#ccd0da40',
      'editor.selectionBackground': '#acb0be66',
      'editor.inactiveSelectionBackground': '#acb0be33',
      'editor.selectionHighlightBackground': '#acb0be40',
      'editor.wordHighlightBackground': '#acb0be40',
      'editor.wordHighlightStrongBackground': '#acb0be55',
      'editor.findMatchBackground': '#df8e1d40',
      'editor.findMatchHighlightBackground': '#df8e1d25',
      'editorCursor.foreground': '#dc8a78',
      'editorLineNumber.foreground': '#9ca0b0',
      'editorLineNumber.activeForeground': '#4c4f69',
      'editorIndentGuide.background': '#ccd0da80',
      'editorIndentGuide.activeBackground': '#bcc0cc80',
      'editorGutter.background': '#eff1f5',
      'editorBracketMatch.background': '#acb0be50',
      'editorBracketMatch.border': '#acb0be',
      'editorWidget.background': '#e6e9ef',
      'editorWidget.border': '#ccd0da',
      'editorWidget.foreground': '#4c4f69',
      'scrollbar.shadow': '#dce0e800',
      'scrollbarSlider.background': '#bcc0cc50',
      'scrollbarSlider.hoverBackground': '#bcc0cc80',
      'scrollbarSlider.activeBackground': '#acb0be',
      'input.background': '#ccd0da',
      'input.foreground': '#4c4f69',
      'input.border': '#bcc0cc',
      'input.placeholderForeground': '#9ca0b0',
      'inputOption.activeBorder': '#1e66f5',
      'dropdown.background': '#e6e9ef',
      'dropdown.border': '#ccd0da',
      'dropdown.foreground': '#4c4f69',
      'list.activeSelectionBackground': '#bcc0cc',
      'list.activeSelectionForeground': '#4c4f69',
      'list.hoverBackground': '#ccd0da',
      'list.focusBackground': '#bcc0cc',
      'list.highlightForeground': '#1e66f5',
      'editorOverviewRuler.border': '#eff1f5',
      'editorSuggestWidget.background': '#e6e9ef',
      'editorSuggestWidget.border': '#ccd0da',
      'editorSuggestWidget.foreground': '#4c4f69',
      'editorSuggestWidget.selectedBackground': '#bcc0cc',
      'editorSuggestWidget.highlightForeground': '#1e66f5',
      'minimap.background': '#eff1f5',
    },
  },
  terminal: {
    background: '#eff1f5',
    foreground: '#4c4f69',
    cursor: '#dc8a78',
    cursorAccent: '#eff1f5',
    selectionBackground: '#acb0be66',
    selectionForeground: '#4c4f69',
    black: '#5c5f77',
    red: '#d20f39',
    green: '#40a02b',
    yellow: '#df8e1d',
    blue: '#1e66f5',
    magenta: '#ea76cb',
    cyan: '#179299',
    white: '#acb0be',
    brightBlack: '#6c6f85',
    brightRed: '#d20f39',
    brightGreen: '#40a02b',
    brightYellow: '#df8e1d',
    brightBlue: '#1e66f5',
    brightMagenta: '#ea76cb',
    brightCyan: '#179299',
    brightWhite: '#bcc0cc',
  },
};
