import { ThemeDefinition } from '../../shared/types';

export const catppuccinMocha: ThemeDefinition = {
  id: 'catppuccin-mocha',
  name: 'Catppuccin Mocha',
  type: 'dark',
  colors: {
    base: '#1e1e2e',
    mantle: '#181825',
    crust: '#11111b',
    text: '#cdd6f4',
    subtext0: '#a6adc8',
    subtext1: '#bac2de',
    surface0: '#313244',
    surface1: '#45475a',
    surface2: '#585b70',
    accent: '#89b4fa',
    link: '#89b4fa',
  },
  hljs: {
    keyword: '#cba6f7',
    string: '#a6e3a1',
    number: '#fab387',
    comment: '#6c7086',
    function: '#89b4fa',
    type: '#f9e2af',
    variable: '#f38ba8',
    regexp: '#f5c2e7',
    tag: '#89b4fa',
    attribute: '#f9e2af',
    symbol: '#f38ba8',
    meta: '#fab387',
    addition: '#a6e3a1',
    deletion: '#f38ba8',
    property: '#94e2d5',
    punctuation: '#9399b2',
  },
  monaco: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'cdd6f4' },
      { token: 'invalid', foreground: 'f38ba8' },
      { token: 'keyword', foreground: 'cba6f7' },
      { token: 'keyword.control', foreground: 'cba6f7' },
      { token: 'keyword.operator', foreground: '89dceb' },
      { token: 'storage', foreground: 'cba6f7' },
      { token: 'storage.type', foreground: 'cba6f7' },
      { token: 'string', foreground: 'a6e3a1' },
      { token: 'string.escape', foreground: 'f5c2e7' },
      { token: 'string.regexp', foreground: 'f5c2e7' },
      { token: 'number', foreground: 'fab387' },
      { token: 'number.hex', foreground: 'fab387' },
      { token: 'constant', foreground: 'fab387' },
      { token: 'comment', foreground: '6c7086', fontStyle: 'italic' },
      { token: 'entity.name.function', foreground: '89b4fa' },
      { token: 'support.function', foreground: '89b4fa' },
      { token: 'meta.function-call', foreground: '89b4fa' },
      { token: 'entity.name.type', foreground: 'f9e2af' },
      { token: 'entity.name.class', foreground: 'f9e2af' },
      { token: 'support.type', foreground: 'f9e2af' },
      { token: 'support.class', foreground: 'f9e2af' },
      { token: 'type', foreground: 'f9e2af' },
      { token: 'type.identifier', foreground: 'f9e2af' },
      { token: 'variable', foreground: 'cdd6f4' },
      { token: 'variable.parameter', foreground: 'f38ba8' },
      { token: 'variable.other', foreground: 'cdd6f4' },
      { token: 'variable.property', foreground: '94e2d5' },
      { token: 'support.variable.property', foreground: '94e2d5' },
      { token: 'tag', foreground: '89b4fa' },
      { token: 'tag.id.pug', foreground: '89b4fa' },
      { token: 'meta.tag', foreground: '89b4fa' },
      { token: 'attribute.name', foreground: 'f9e2af' },
      { token: 'attribute.value', foreground: 'a6e3a1' },
      { token: 'inserted', foreground: 'a6e3a1' },
      { token: 'deleted', foreground: 'f38ba8' },
      { token: 'delimiter', foreground: '9399b2' },
      { token: 'delimiter.bracket', foreground: '9399b2' },
      { token: 'punctuation', foreground: '9399b2' },
      { token: 'meta', foreground: 'fab387' },
      { token: 'annotation', foreground: 'fab387' },
      { token: 'metatag', foreground: 'fab387' },
      { token: 'operator', foreground: '89dceb' },
      { token: 'string.key.json', foreground: '89b4fa' },
      { token: 'string.value.json', foreground: 'a6e3a1' },
      { token: 'type.yaml', foreground: '89b4fa' },
      { token: 'markup.heading', foreground: '89b4fa', fontStyle: 'bold' },
      { token: 'markup.bold', fontStyle: 'bold' },
      { token: 'markup.italic', fontStyle: 'italic' },
      { token: 'markup.inline', foreground: 'f38ba8' },
      { token: 'markup.underline.link', foreground: '89b4fa' },
    ],
    colors: {
      'editor.background': '#1e1e2e',
      'editor.foreground': '#cdd6f4',
      'editor.lineHighlightBackground': '#31324440',
      'editor.selectionBackground': '#585b7066',
      'editor.inactiveSelectionBackground': '#585b7033',
      'editor.selectionHighlightBackground': '#585b7040',
      'editor.wordHighlightBackground': '#585b7040',
      'editor.wordHighlightStrongBackground': '#585b7055',
      'editor.findMatchBackground': '#f9e2af40',
      'editor.findMatchHighlightBackground': '#f9e2af25',
      'editorCursor.foreground': '#f5e0dc',
      'editorLineNumber.foreground': '#6c7086',
      'editorLineNumber.activeForeground': '#cdd6f4',
      'editorIndentGuide.background': '#31324480',
      'editorIndentGuide.activeBackground': '#45475a80',
      'editorGutter.background': '#1e1e2e',
      'editorBracketMatch.background': '#585b7050',
      'editorBracketMatch.border': '#585b70',
      'editorWidget.background': '#181825',
      'editorWidget.border': '#313244',
      'editorWidget.foreground': '#cdd6f4',
      'scrollbar.shadow': '#11111b00',
      'scrollbarSlider.background': '#45475a50',
      'scrollbarSlider.hoverBackground': '#45475a80',
      'scrollbarSlider.activeBackground': '#585b70',
      'input.background': '#313244',
      'input.foreground': '#cdd6f4',
      'input.border': '#45475a',
      'input.placeholderForeground': '#6c7086',
      'inputOption.activeBorder': '#89b4fa',
      'dropdown.background': '#181825',
      'dropdown.border': '#313244',
      'dropdown.foreground': '#cdd6f4',
      'list.activeSelectionBackground': '#45475a',
      'list.activeSelectionForeground': '#cdd6f4',
      'list.hoverBackground': '#313244',
      'list.focusBackground': '#45475a',
      'list.highlightForeground': '#89b4fa',
      'editorOverviewRuler.border': '#1e1e2e',
      'editorOverviewRuler.findMatchForeground': '#f9e2af60',
      'editorOverviewRuler.selectionHighlightForeground': '#585b7060',
      'editorSuggestWidget.background': '#181825',
      'editorSuggestWidget.border': '#313244',
      'editorSuggestWidget.foreground': '#cdd6f4',
      'editorSuggestWidget.selectedBackground': '#45475a',
      'editorSuggestWidget.highlightForeground': '#89b4fa',
      'peekView.border': '#45475a',
      'peekViewEditor.background': '#181825',
      'peekViewResult.background': '#181825',
      'peekViewTitle.background': '#181825',
      'minimap.background': '#1e1e2e',
    },
  },
  terminal: {
    background: '#1e1e2e',
    foreground: '#cdd6f4',
    cursor: '#f5e0dc',
    cursorAccent: '#1e1e2e',
    selectionBackground: '#585b7066',
    selectionForeground: '#cdd6f4',
    black: '#45475a',
    red: '#f38ba8',
    green: '#a6e3a1',
    yellow: '#f9e2af',
    blue: '#89b4fa',
    magenta: '#f5c2e7',
    cyan: '#94e2d5',
    white: '#bac2de',
    brightBlack: '#585b70',
    brightRed: '#f38ba8',
    brightGreen: '#a6e3a1',
    brightYellow: '#f9e2af',
    brightBlue: '#89b4fa',
    brightMagenta: '#f5c2e7',
    brightCyan: '#94e2d5',
    brightWhite: '#a6adc8',
  },
};
