import { ThemeDefinition } from '../../shared/types';

export const dracula: ThemeDefinition = {
  id: 'dracula',
  name: 'Dracula',
  type: 'dark',
  colors: {
    base: '#282a36',
    mantle: '#21222c',
    crust: '#191a21',
    text: '#f8f8f2',
    subtext0: '#8791ad',
    subtext1: '#bfc5d4',
    surface0: '#343746',
    surface1: '#44475a',
    surface2: '#565970',
    accent: '#bd93f9',
    link: '#8be9fd',
  },
  hljs: {
    keyword: '#ff79c6',
    string: '#f1fa8c',
    number: '#bd93f9',
    comment: '#6272a4',
    function: '#50fa7b',
    type: '#8be9fd',
    variable: '#ffb86c',
    regexp: '#ff5555',
    tag: '#ff79c6',
    attribute: '#50fa7b',
    symbol: '#ffb86c',
    meta: '#ff79c6',
    addition: '#50fa7b',
    deletion: '#ff5555',
    property: '#66d9ef',
    punctuation: '#f8f8f2',
  },
  monaco: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'f8f8f2' },
      { token: 'invalid', foreground: 'ff5555' },
      { token: 'keyword', foreground: 'ff79c6' },
      { token: 'keyword.control', foreground: 'ff79c6' },
      { token: 'keyword.operator', foreground: 'ff79c6' },
      { token: 'storage', foreground: 'ff79c6' },
      { token: 'storage.type', foreground: '8be9fd' },
      { token: 'string', foreground: 'f1fa8c' },
      { token: 'string.escape', foreground: 'ff79c6' },
      { token: 'string.regexp', foreground: 'ff5555' },
      { token: 'number', foreground: 'bd93f9' },
      { token: 'number.hex', foreground: 'bd93f9' },
      { token: 'constant', foreground: 'bd93f9' },
      { token: 'comment', foreground: '6272a4', fontStyle: 'italic' },
      { token: 'entity.name.function', foreground: '50fa7b' },
      { token: 'support.function', foreground: '50fa7b' },
      { token: 'entity.name.type', foreground: '8be9fd' },
      { token: 'entity.name.class', foreground: '8be9fd' },
      { token: 'support.type', foreground: '8be9fd' },
      { token: 'type', foreground: '8be9fd' },
      { token: 'type.identifier', foreground: '8be9fd' },
      { token: 'variable', foreground: 'f8f8f2' },
      { token: 'variable.parameter', foreground: 'ffb86c' },
      { token: 'variable.property', foreground: '66d9ef' },
      { token: 'tag', foreground: 'ff79c6' },
      { token: 'attribute.name', foreground: '50fa7b' },
      { token: 'attribute.value', foreground: 'f1fa8c' },
      { token: 'inserted', foreground: '50fa7b' },
      { token: 'deleted', foreground: 'ff5555' },
      { token: 'delimiter', foreground: 'f8f8f2' },
      { token: 'punctuation', foreground: 'f8f8f2' },
      { token: 'operator', foreground: 'ff79c6' },
      { token: 'string.key.json', foreground: '8be9fd' },
      { token: 'string.value.json', foreground: 'f1fa8c' },
      { token: 'type.yaml', foreground: '8be9fd' },
      { token: 'markup.heading', foreground: 'bd93f9', fontStyle: 'bold' },
      { token: 'markup.bold', fontStyle: 'bold' },
      { token: 'markup.italic', fontStyle: 'italic' },
      { token: 'markup.inline', foreground: 'ffb86c' },
      { token: 'markup.underline.link', foreground: '8be9fd' },
    ],
    colors: {
      'editor.background': '#282a36',
      'editor.foreground': '#f8f8f2',
      'editor.lineHighlightBackground': '#34374640',
      'editor.selectionBackground': '#44475a99',
      'editor.inactiveSelectionBackground': '#44475a44',
      'editor.selectionHighlightBackground': '#44475a55',
      'editor.findMatchBackground': '#f1fa8c40',
      'editor.findMatchHighlightBackground': '#f1fa8c25',
      'editorCursor.foreground': '#f8f8f2',
      'editorLineNumber.foreground': '#6272a4',
      'editorLineNumber.activeForeground': '#f8f8f2',
      'editorIndentGuide.background': '#34374680',
      'editorIndentGuide.activeBackground': '#44475a80',
      'editorGutter.background': '#282a36',
      'editorBracketMatch.background': '#44475a50',
      'editorBracketMatch.border': '#44475a',
      'editorWidget.background': '#21222c',
      'editorWidget.border': '#343746',
      'editorWidget.foreground': '#f8f8f2',
      'scrollbarSlider.background': '#44475a50',
      'scrollbarSlider.hoverBackground': '#44475a80',
      'scrollbarSlider.activeBackground': '#565970',
      'input.background': '#343746',
      'input.foreground': '#f8f8f2',
      'input.border': '#44475a',
      'dropdown.background': '#21222c',
      'dropdown.border': '#343746',
      'dropdown.foreground': '#f8f8f2',
      'list.activeSelectionBackground': '#44475a',
      'list.activeSelectionForeground': '#f8f8f2',
      'list.hoverBackground': '#343746',
      'list.highlightForeground': '#8be9fd',
      'editorSuggestWidget.background': '#21222c',
      'editorSuggestWidget.border': '#343746',
      'editorSuggestWidget.foreground': '#f8f8f2',
      'editorSuggestWidget.selectedBackground': '#44475a',
      'editorSuggestWidget.highlightForeground': '#8be9fd',
      'minimap.background': '#282a36',
    },
  },
  terminal: {
    background: '#282a36',
    foreground: '#f8f8f2',
    cursor: '#f8f8f2',
    cursorAccent: '#282a36',
    selectionBackground: '#44475a99',
    selectionForeground: '#f8f8f2',
    black: '#21222c',
    red: '#ff5555',
    green: '#50fa7b',
    yellow: '#f1fa8c',
    blue: '#bd93f9',
    magenta: '#ff79c6',
    cyan: '#8be9fd',
    white: '#f8f8f2',
    brightBlack: '#6272a4',
    brightRed: '#ff6e6e',
    brightGreen: '#69ff94',
    brightYellow: '#ffffa5',
    brightBlue: '#d6acff',
    brightMagenta: '#ff92df',
    brightCyan: '#a4ffff',
    brightWhite: '#ffffff',
  },
};
