import { ThemeDefinition } from '../../shared/types';

export const gruvboxDark: ThemeDefinition = {
  id: 'gruvbox-dark',
  name: 'Gruvbox Dark',
  type: 'dark',
  colors: {
    base: '#282828',
    mantle: '#1d2021',
    crust: '#141617',
    text: '#ebdbb2',
    subtext0: '#a89984',
    subtext1: '#bdae93',
    surface0: '#3c3836',
    surface1: '#504945',
    surface2: '#665c54',
    accent: '#83a598',
    link: '#83a598',
  },
  hljs: {
    keyword: '#fb4934',
    string: '#b8bb26',
    number: '#d3869b',
    comment: '#928374',
    function: '#fabd2f',
    type: '#83a598',
    variable: '#fe8019',
    regexp: '#8ec07c',
    tag: '#fb4934',
    attribute: '#fabd2f',
    symbol: '#fe8019',
    meta: '#d3869b',
    addition: '#b8bb26',
    deletion: '#fb4934',
    property: '#8ec07c',
    punctuation: '#a89984',
  },
  monaco: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'ebdbb2' },
      { token: 'invalid', foreground: 'fb4934' },
      { token: 'keyword', foreground: 'fb4934' },
      { token: 'keyword.control', foreground: 'fb4934' },
      { token: 'keyword.operator', foreground: 'fe8019' },
      { token: 'storage', foreground: 'fb4934' },
      { token: 'storage.type', foreground: 'fb4934' },
      { token: 'string', foreground: 'b8bb26' },
      { token: 'string.escape', foreground: 'fe8019' },
      { token: 'string.regexp', foreground: '8ec07c' },
      { token: 'number', foreground: 'd3869b' },
      { token: 'number.hex', foreground: 'd3869b' },
      { token: 'constant', foreground: 'd3869b' },
      { token: 'comment', foreground: '928374', fontStyle: 'italic' },
      { token: 'entity.name.function', foreground: 'fabd2f' },
      { token: 'support.function', foreground: 'fabd2f' },
      { token: 'entity.name.type', foreground: '83a598' },
      { token: 'entity.name.class', foreground: '83a598' },
      { token: 'support.type', foreground: '83a598' },
      { token: 'type', foreground: '83a598' },
      { token: 'type.identifier', foreground: '83a598' },
      { token: 'variable', foreground: 'ebdbb2' },
      { token: 'variable.parameter', foreground: 'fe8019' },
      { token: 'variable.property', foreground: '8ec07c' },
      { token: 'tag', foreground: 'fb4934' },
      { token: 'attribute.name', foreground: 'fabd2f' },
      { token: 'attribute.value', foreground: 'b8bb26' },
      { token: 'inserted', foreground: 'b8bb26' },
      { token: 'deleted', foreground: 'fb4934' },
      { token: 'delimiter', foreground: 'a89984' },
      { token: 'punctuation', foreground: 'a89984' },
      { token: 'operator', foreground: 'fe8019' },
      { token: 'string.key.json', foreground: '83a598' },
      { token: 'string.value.json', foreground: 'b8bb26' },
      { token: 'type.yaml', foreground: '83a598' },
      { token: 'markup.heading', foreground: 'fabd2f', fontStyle: 'bold' },
      { token: 'markup.bold', fontStyle: 'bold' },
      { token: 'markup.italic', fontStyle: 'italic' },
      { token: 'markup.inline', foreground: 'fe8019' },
      { token: 'markup.underline.link', foreground: '83a598' },
    ],
    colors: {
      'editor.background': '#282828',
      'editor.foreground': '#ebdbb2',
      'editor.lineHighlightBackground': '#3c383640',
      'editor.selectionBackground': '#665c5466',
      'editor.inactiveSelectionBackground': '#665c5433',
      'editor.selectionHighlightBackground': '#665c5440',
      'editor.findMatchBackground': '#fabd2f40',
      'editor.findMatchHighlightBackground': '#fabd2f25',
      'editorCursor.foreground': '#ebdbb2',
      'editorLineNumber.foreground': '#928374',
      'editorLineNumber.activeForeground': '#ebdbb2',
      'editorIndentGuide.background': '#3c383680',
      'editorIndentGuide.activeBackground': '#50494580',
      'editorGutter.background': '#282828',
      'editorBracketMatch.background': '#665c5450',
      'editorBracketMatch.border': '#665c54',
      'editorWidget.background': '#1d2021',
      'editorWidget.border': '#3c3836',
      'editorWidget.foreground': '#ebdbb2',
      'scrollbarSlider.background': '#50494550',
      'scrollbarSlider.hoverBackground': '#50494580',
      'scrollbarSlider.activeBackground': '#665c54',
      'input.background': '#3c3836',
      'input.foreground': '#ebdbb2',
      'input.border': '#504945',
      'dropdown.background': '#1d2021',
      'dropdown.border': '#3c3836',
      'dropdown.foreground': '#ebdbb2',
      'list.activeSelectionBackground': '#504945',
      'list.activeSelectionForeground': '#ebdbb2',
      'list.hoverBackground': '#3c3836',
      'list.highlightForeground': '#83a598',
      'editorSuggestWidget.background': '#1d2021',
      'editorSuggestWidget.border': '#3c3836',
      'editorSuggestWidget.foreground': '#ebdbb2',
      'editorSuggestWidget.selectedBackground': '#504945',
      'editorSuggestWidget.highlightForeground': '#83a598',
      'minimap.background': '#282828',
    },
  },
  terminal: {
    background: '#282828',
    foreground: '#ebdbb2',
    cursor: '#ebdbb2',
    cursorAccent: '#282828',
    selectionBackground: '#665c5466',
    selectionForeground: '#ebdbb2',
    black: '#3c3836',
    red: '#fb4934',
    green: '#b8bb26',
    yellow: '#fabd2f',
    blue: '#83a598',
    magenta: '#d3869b',
    cyan: '#8ec07c',
    white: '#d5c4a1',
    brightBlack: '#665c54',
    brightRed: '#fb4934',
    brightGreen: '#b8bb26',
    brightYellow: '#fabd2f',
    brightBlue: '#83a598',
    brightMagenta: '#d3869b',
    brightCyan: '#8ec07c',
    brightWhite: '#fbf1c7',
  },
};
