import { ThemeDefinition } from '../../shared/types';

export const nord: ThemeDefinition = {
  id: 'nord',
  name: 'Nord',
  type: 'dark',
  colors: {
    base: '#2e3440',
    mantle: '#292e39',
    crust: '#242933',
    text: '#d8dee9',
    subtext0: '#7b88a1',
    subtext1: '#a3b1cc',
    surface0: '#3b4252',
    surface1: '#434c5e',
    surface2: '#4c566a',
    accent: '#88c0d0',
    link: '#88c0d0',
  },
  hljs: {
    keyword: '#81a1c1',
    string: '#a3be8c',
    number: '#b48ead',
    comment: '#616e88',
    function: '#88c0d0',
    type: '#ebcb8b',
    variable: '#d08770',
    regexp: '#bf616a',
    tag: '#81a1c1',
    attribute: '#8fbcbb',
    symbol: '#d08770',
    meta: '#5e81ac',
    addition: '#a3be8c',
    deletion: '#bf616a',
    property: '#8fbcbb',
    punctuation: '#81a1c1',
  },
  monaco: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'd8dee9' },
      { token: 'invalid', foreground: 'bf616a' },
      { token: 'keyword', foreground: '81a1c1' },
      { token: 'keyword.control', foreground: '81a1c1' },
      { token: 'keyword.operator', foreground: '81a1c1' },
      { token: 'storage', foreground: '81a1c1' },
      { token: 'storage.type', foreground: '81a1c1' },
      { token: 'string', foreground: 'a3be8c' },
      { token: 'string.escape', foreground: 'ebcb8b' },
      { token: 'string.regexp', foreground: 'bf616a' },
      { token: 'number', foreground: 'b48ead' },
      { token: 'number.hex', foreground: 'b48ead' },
      { token: 'constant', foreground: 'b48ead' },
      { token: 'comment', foreground: '616e88', fontStyle: 'italic' },
      { token: 'entity.name.function', foreground: '88c0d0' },
      { token: 'support.function', foreground: '88c0d0' },
      { token: 'entity.name.type', foreground: 'ebcb8b' },
      { token: 'entity.name.class', foreground: 'ebcb8b' },
      { token: 'support.type', foreground: 'ebcb8b' },
      { token: 'type', foreground: 'ebcb8b' },
      { token: 'type.identifier', foreground: 'ebcb8b' },
      { token: 'variable', foreground: 'd8dee9' },
      { token: 'variable.parameter', foreground: 'd08770' },
      { token: 'variable.property', foreground: '8fbcbb' },
      { token: 'tag', foreground: '81a1c1' },
      { token: 'attribute.name', foreground: '8fbcbb' },
      { token: 'attribute.value', foreground: 'a3be8c' },
      { token: 'inserted', foreground: 'a3be8c' },
      { token: 'deleted', foreground: 'bf616a' },
      { token: 'delimiter', foreground: '81a1c1' },
      { token: 'punctuation', foreground: '81a1c1' },
      { token: 'operator', foreground: '81a1c1' },
      { token: 'string.key.json', foreground: '88c0d0' },
      { token: 'string.value.json', foreground: 'a3be8c' },
      { token: 'type.yaml', foreground: '88c0d0' },
      { token: 'markup.heading', foreground: '88c0d0', fontStyle: 'bold' },
      { token: 'markup.bold', fontStyle: 'bold' },
      { token: 'markup.italic', fontStyle: 'italic' },
      { token: 'markup.inline', foreground: 'bf616a' },
      { token: 'markup.underline.link', foreground: '88c0d0' },
    ],
    colors: {
      'editor.background': '#2e3440',
      'editor.foreground': '#d8dee9',
      'editor.lineHighlightBackground': '#3b425240',
      'editor.selectionBackground': '#4c566a66',
      'editor.inactiveSelectionBackground': '#4c566a33',
      'editor.selectionHighlightBackground': '#4c566a40',
      'editor.findMatchBackground': '#ebcb8b40',
      'editor.findMatchHighlightBackground': '#ebcb8b25',
      'editorCursor.foreground': '#d8dee9',
      'editorLineNumber.foreground': '#616e88',
      'editorLineNumber.activeForeground': '#d8dee9',
      'editorIndentGuide.background': '#3b425280',
      'editorIndentGuide.activeBackground': '#434c5e80',
      'editorGutter.background': '#2e3440',
      'editorBracketMatch.background': '#4c566a50',
      'editorBracketMatch.border': '#4c566a',
      'editorWidget.background': '#292e39',
      'editorWidget.border': '#3b4252',
      'editorWidget.foreground': '#d8dee9',
      'scrollbarSlider.background': '#434c5e50',
      'scrollbarSlider.hoverBackground': '#434c5e80',
      'scrollbarSlider.activeBackground': '#4c566a',
      'input.background': '#3b4252',
      'input.foreground': '#d8dee9',
      'input.border': '#434c5e',
      'dropdown.background': '#292e39',
      'dropdown.border': '#3b4252',
      'dropdown.foreground': '#d8dee9',
      'list.activeSelectionBackground': '#434c5e',
      'list.activeSelectionForeground': '#d8dee9',
      'list.hoverBackground': '#3b4252',
      'list.highlightForeground': '#88c0d0',
      'editorSuggestWidget.background': '#292e39',
      'editorSuggestWidget.border': '#3b4252',
      'editorSuggestWidget.foreground': '#d8dee9',
      'editorSuggestWidget.selectedBackground': '#434c5e',
      'editorSuggestWidget.highlightForeground': '#88c0d0',
      'minimap.background': '#2e3440',
    },
  },
  terminal: {
    background: '#2e3440',
    foreground: '#d8dee9',
    cursor: '#d8dee9',
    cursorAccent: '#2e3440',
    selectionBackground: '#4c566a66',
    selectionForeground: '#d8dee9',
    black: '#3b4252',
    red: '#bf616a',
    green: '#a3be8c',
    yellow: '#ebcb8b',
    blue: '#81a1c1',
    magenta: '#b48ead',
    cyan: '#88c0d0',
    white: '#e5e9f0',
    brightBlack: '#4c566a',
    brightRed: '#bf616a',
    brightGreen: '#a3be8c',
    brightYellow: '#ebcb8b',
    brightBlue: '#81a1c1',
    brightMagenta: '#b48ead',
    brightCyan: '#8fbcbb',
    brightWhite: '#eceff4',
  },
};
