import { ThemeDefinition } from '../../shared/types';

export const terminalTheme: ThemeDefinition = {
  id: 'terminal',
  name: 'Terminal',
  type: 'dark',
  fontOverride: "'SF Mono', 'Fira Code', 'Cascadia Code', Menlo, monospace",
  colors: {
    base: '#0a0a0a',
    mantle: '#050505',
    crust: '#000000',
    text: '#00ff00',
    subtext0: '#00aa00',
    subtext1: '#00cc00',
    surface0: '#1a1a1a',
    surface1: '#252525',
    surface2: '#333333',
    accent: '#00ff00',
    link: '#00ff00',
  },
  hljs: {
    keyword: '#00ff00',
    string: '#00cc00',
    number: '#00ffaa',
    comment: '#006600',
    function: '#00ff66',
    type: '#00ffcc',
    variable: '#00dd00',
    regexp: '#00ff99',
    tag: '#00ff66',
    attribute: '#00ffcc',
    symbol: '#00dd00',
    meta: '#00ffaa',
    addition: '#00ff00',
    deletion: '#ff3333',
    property: '#00ff88',
    punctuation: '#008800',
  },
  monaco: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: '00ff00' },
      { token: 'invalid', foreground: 'ff3333' },
      { token: 'keyword', foreground: '00ff00' },
      { token: 'keyword.control', foreground: '00ff00' },
      { token: 'keyword.operator', foreground: '00cc00' },
      { token: 'storage', foreground: '00ff00' },
      { token: 'string', foreground: '00cc00' },
      { token: 'string.escape', foreground: '00ff99' },
      { token: 'string.regexp', foreground: '00ff99' },
      { token: 'number', foreground: '00ffaa' },
      { token: 'constant', foreground: '00ffaa' },
      { token: 'comment', foreground: '006600', fontStyle: 'italic' },
      { token: 'entity.name.function', foreground: '00ff66' },
      { token: 'support.function', foreground: '00ff66' },
      { token: 'entity.name.type', foreground: '00ffcc' },
      { token: 'support.type', foreground: '00ffcc' },
      { token: 'type', foreground: '00ffcc' },
      { token: 'type.identifier', foreground: '00ffcc' },
      { token: 'variable', foreground: '00dd00' },
      { token: 'variable.parameter', foreground: '00dd00' },
      { token: 'variable.property', foreground: '00ff88' },
      { token: 'tag', foreground: '00ff66' },
      { token: 'attribute.name', foreground: '00ffcc' },
      { token: 'attribute.value', foreground: '00cc00' },
      { token: 'inserted', foreground: '00ff00' },
      { token: 'deleted', foreground: 'ff3333' },
      { token: 'delimiter', foreground: '008800' },
      { token: 'punctuation', foreground: '008800' },
      { token: 'operator', foreground: '00cc00' },
      { token: 'string.key.json', foreground: '00ff66' },
      { token: 'string.value.json', foreground: '00cc00' },
      { token: 'markup.heading', foreground: '00ff00', fontStyle: 'bold' },
    ],
    colors: {
      'editor.background': '#0a0a0a',
      'editor.foreground': '#00ff00',
      'editor.lineHighlightBackground': '#1a1a1a40',
      'editor.selectionBackground': '#33333366',
      'editor.inactiveSelectionBackground': '#33333333',
      'editor.selectionHighlightBackground': '#33333340',
      'editor.findMatchBackground': '#00ff0040',
      'editor.findMatchHighlightBackground': '#00ff0020',
      'editorCursor.foreground': '#00ff00',
      'editorLineNumber.foreground': '#006600',
      'editorLineNumber.activeForeground': '#00ff00',
      'editorIndentGuide.background': '#1a1a1a80',
      'editorIndentGuide.activeBackground': '#25252580',
      'editorGutter.background': '#0a0a0a',
      'editorBracketMatch.background': '#33333350',
      'editorBracketMatch.border': '#333333',
      'editorWidget.background': '#050505',
      'editorWidget.border': '#1a1a1a',
      'editorWidget.foreground': '#00ff00',
      'scrollbarSlider.background': '#25252550',
      'scrollbarSlider.hoverBackground': '#25252580',
      'scrollbarSlider.activeBackground': '#333333',
      'input.background': '#1a1a1a',
      'input.foreground': '#00ff00',
      'input.border': '#252525',
      'dropdown.background': '#050505',
      'dropdown.border': '#1a1a1a',
      'dropdown.foreground': '#00ff00',
      'list.activeSelectionBackground': '#252525',
      'list.activeSelectionForeground': '#00ff00',
      'list.hoverBackground': '#1a1a1a',
      'list.highlightForeground': '#00ff00',
      'editorSuggestWidget.background': '#050505',
      'editorSuggestWidget.border': '#1a1a1a',
      'editorSuggestWidget.foreground': '#00ff00',
      'editorSuggestWidget.selectedBackground': '#252525',
      'editorSuggestWidget.highlightForeground': '#00ff00',
      'minimap.background': '#0a0a0a',
    },
  },
  terminal: {
    background: '#0a0a0a',
    foreground: '#00ff00',
    cursor: '#00ff00',
    cursorAccent: '#0a0a0a',
    selectionBackground: '#33333366',
    selectionForeground: '#00ff00',
    black: '#1a1a1a',
    red: '#ff3333',
    green: '#00ff00',
    yellow: '#ffff00',
    blue: '#00aaff',
    magenta: '#ff00ff',
    cyan: '#00ffff',
    white: '#00cc00',
    brightBlack: '#333333',
    brightRed: '#ff6666',
    brightGreen: '#33ff33',
    brightYellow: '#ffff66',
    brightBlue: '#66ccff',
    brightMagenta: '#ff66ff',
    brightCyan: '#66ffff',
    brightWhite: '#00ff00',
  },
};
