import { ThemeDefinition } from '../../shared/types';

export const tokyoNight: ThemeDefinition = {
  id: 'tokyo-night',
  name: 'Tokyo Night',
  type: 'dark',
  colors: {
    base: '#1a1b26',
    mantle: '#16161e',
    crust: '#101014',
    text: '#a9b1d6',
    subtext0: '#737aa2',
    subtext1: '#9aa5ce',
    surface0: '#24283b',
    surface1: '#2f3549',
    surface2: '#3b4261',
    accent: '#7aa2f7',
    link: '#7aa2f7',
  },
  hljs: {
    keyword: '#bb9af7',
    string: '#9ece6a',
    number: '#ff9e64',
    comment: '#565f89',
    function: '#7aa2f7',
    type: '#e0af68',
    variable: '#f7768e',
    regexp: '#b4f9f8',
    tag: '#7aa2f7',
    attribute: '#e0af68',
    symbol: '#f7768e',
    meta: '#ff9e64',
    addition: '#9ece6a',
    deletion: '#f7768e',
    property: '#73daca',
    punctuation: '#9aa5ce',
  },
  monaco: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'a9b1d6' },
      { token: 'invalid', foreground: 'f7768e' },
      { token: 'keyword', foreground: 'bb9af7' },
      { token: 'keyword.control', foreground: 'bb9af7' },
      { token: 'keyword.operator', foreground: '89ddff' },
      { token: 'storage', foreground: 'bb9af7' },
      { token: 'storage.type', foreground: 'bb9af7' },
      { token: 'string', foreground: '9ece6a' },
      { token: 'string.escape', foreground: 'bb9af7' },
      { token: 'string.regexp', foreground: 'b4f9f8' },
      { token: 'number', foreground: 'ff9e64' },
      { token: 'number.hex', foreground: 'ff9e64' },
      { token: 'constant', foreground: 'ff9e64' },
      { token: 'comment', foreground: '565f89', fontStyle: 'italic' },
      { token: 'entity.name.function', foreground: '7aa2f7' },
      { token: 'support.function', foreground: '7aa2f7' },
      { token: 'entity.name.type', foreground: 'e0af68' },
      { token: 'entity.name.class', foreground: 'e0af68' },
      { token: 'support.type', foreground: 'e0af68' },
      { token: 'type', foreground: 'e0af68' },
      { token: 'type.identifier', foreground: 'e0af68' },
      { token: 'variable', foreground: 'a9b1d6' },
      { token: 'variable.parameter', foreground: 'f7768e' },
      { token: 'variable.property', foreground: '73daca' },
      { token: 'tag', foreground: '7aa2f7' },
      { token: 'attribute.name', foreground: 'e0af68' },
      { token: 'attribute.value', foreground: '9ece6a' },
      { token: 'inserted', foreground: '9ece6a' },
      { token: 'deleted', foreground: 'f7768e' },
      { token: 'delimiter', foreground: '9aa5ce' },
      { token: 'punctuation', foreground: '9aa5ce' },
      { token: 'operator', foreground: '89ddff' },
      { token: 'string.key.json', foreground: '7aa2f7' },
      { token: 'string.value.json', foreground: '9ece6a' },
      { token: 'type.yaml', foreground: '7aa2f7' },
      { token: 'markup.heading', foreground: '7aa2f7', fontStyle: 'bold' },
      { token: 'markup.bold', fontStyle: 'bold' },
      { token: 'markup.italic', fontStyle: 'italic' },
      { token: 'markup.inline', foreground: 'f7768e' },
      { token: 'markup.underline.link', foreground: '7aa2f7' },
    ],
    colors: {
      'editor.background': '#1a1b26',
      'editor.foreground': '#a9b1d6',
      'editor.lineHighlightBackground': '#24283b40',
      'editor.selectionBackground': '#3b426166',
      'editor.inactiveSelectionBackground': '#3b426133',
      'editor.selectionHighlightBackground': '#3b426140',
      'editor.findMatchBackground': '#e0af6840',
      'editor.findMatchHighlightBackground': '#e0af6825',
      'editorCursor.foreground': '#c0caf5',
      'editorLineNumber.foreground': '#565f89',
      'editorLineNumber.activeForeground': '#a9b1d6',
      'editorIndentGuide.background': '#24283b80',
      'editorIndentGuide.activeBackground': '#2f354980',
      'editorGutter.background': '#1a1b26',
      'editorBracketMatch.background': '#3b426150',
      'editorBracketMatch.border': '#3b4261',
      'editorWidget.background': '#16161e',
      'editorWidget.border': '#24283b',
      'editorWidget.foreground': '#a9b1d6',
      'scrollbarSlider.background': '#2f354950',
      'scrollbarSlider.hoverBackground': '#2f354980',
      'scrollbarSlider.activeBackground': '#3b4261',
      'input.background': '#24283b',
      'input.foreground': '#a9b1d6',
      'input.border': '#2f3549',
      'dropdown.background': '#16161e',
      'dropdown.border': '#24283b',
      'dropdown.foreground': '#a9b1d6',
      'list.activeSelectionBackground': '#2f3549',
      'list.activeSelectionForeground': '#a9b1d6',
      'list.hoverBackground': '#24283b',
      'list.highlightForeground': '#7aa2f7',
      'editorSuggestWidget.background': '#16161e',
      'editorSuggestWidget.border': '#24283b',
      'editorSuggestWidget.foreground': '#a9b1d6',
      'editorSuggestWidget.selectedBackground': '#2f3549',
      'editorSuggestWidget.highlightForeground': '#7aa2f7',
      'minimap.background': '#1a1b26',
    },
  },
  terminal: {
    background: '#1a1b26',
    foreground: '#a9b1d6',
    cursor: '#c0caf5',
    cursorAccent: '#1a1b26',
    selectionBackground: '#3b426166',
    selectionForeground: '#a9b1d6',
    black: '#414868',
    red: '#f7768e',
    green: '#9ece6a',
    yellow: '#e0af68',
    blue: '#7aa2f7',
    magenta: '#bb9af7',
    cyan: '#7dcfff',
    white: '#c0caf5',
    brightBlack: '#565f89',
    brightRed: '#f7768e',
    brightGreen: '#9ece6a',
    brightYellow: '#e0af68',
    brightBlue: '#7aa2f7',
    brightMagenta: '#bb9af7',
    brightCyan: '#7dcfff',
    brightWhite: '#c0caf5',
  },
};
