export const IPC = {
  PTY: {
    SPAWN: 'pty:spawn',
    SPAWN_SHELL: 'pty:spawn-shell',
    WRITE: 'pty:write',
    RESIZE: 'pty:resize',
    KILL: 'pty:kill',
    GET_BUFFER: 'pty:get-buffer',
    DATA: 'pty:data',
    EXIT: 'pty:exit',
  },
  PROJECT: {
    LIST: 'project:list',
    ADD: 'project:add',
    REMOVE: 'project:remove',
    PICK_DIR: 'project:pick-dir',
    CHECK_GIT: 'project:check-git',
    GIT_INIT: 'project:git-init',
    UPDATE: 'project:update',
    PICK_ICON: 'project:pick-icon',
    REORDER: 'project:reorder',
    READ_ICON: 'project:read-icon',
  },
  AGENT: {
    CREATE_DURABLE: 'agent:create-durable',
    LIST_DURABLE: 'agent:list-durable',
    DELETE_DURABLE: 'agent:delete-durable',
    GET_SETTINGS: 'agent:get-settings',
    SAVE_SETTINGS: 'agent:save-settings',
    READ_CLAUDE_MD: 'agent:read-claude-md',
    SAVE_CLAUDE_MD: 'agent:save-claude-md',
    READ_MCP_CONFIG: 'agent:read-mcp-config',
    LIST_SKILLS: 'agent:list-skills',
    SETUP_HOOKS: 'agent:setup-hooks',
    HOOK_EVENT: 'agent:hook-event',
    GET_WORKTREE_STATUS: 'agent:get-worktree-status',
    DELETE_COMMIT_PUSH: 'agent:delete-commit-push',
    DELETE_CLEANUP_BRANCH: 'agent:delete-cleanup-branch',
    DELETE_SAVE_PATCH: 'agent:delete-save-patch',
    DELETE_FORCE: 'agent:delete-force',
    DELETE_UNREGISTER: 'agent:delete-unregister',
    RENAME_DURABLE: 'agent:rename-durable',
    UPDATE_DURABLE: 'agent:update-durable',
    READ_QUICK_SUMMARY: 'agent:read-quick-summary',
    GET_LOCAL_SETTINGS: 'agent:get-local-settings',
    SAVE_LOCAL_SETTINGS: 'agent:save-local-settings',
    TOGGLE_OVERRIDE: 'agent:toggle-override',
    PREPARE_SPAWN: 'agent:prepare-spawn',
    RESOLVE_QUICK_CONFIG: 'agent:resolve-quick-config',
    GET_DURABLE_CONFIG: 'agent:get-durable-config',
    UPDATE_DURABLE_CONFIG: 'agent:update-durable-config',
  },
  FILE: {
    READ_TREE: 'file:read-tree',
    READ: 'file:read',
    READ_BINARY: 'file:read-binary',
    WRITE: 'file:write',
    SHOW_IN_FOLDER: 'file:show-in-folder',
    MKDIR: 'file:mkdir',
    DELETE: 'file:delete',
  },
  GIT: {
    INFO: 'git:info',
    CHECKOUT: 'git:checkout',
    STAGE: 'git:stage',
    UNSTAGE: 'git:unstage',
    STAGE_ALL: 'git:stage-all',
    UNSTAGE_ALL: 'git:unstage-all',
    DISCARD: 'git:discard',
    COMMIT: 'git:commit',
    PUSH: 'git:push',
    PULL: 'git:pull',
    DIFF: 'git:diff',
    CREATE_BRANCH: 'git:create-branch',
    STASH: 'git:stash',
    STASH_POP: 'git:stash-pop',
  },
  WATCH: {
    START: 'watch:start',
    STOP: 'watch:stop',
    EVENT: 'watch:event',
  },
  APP: {
    OPEN_SETTINGS: 'app:open-settings',
    GET_NOTIFICATION_SETTINGS: 'app:get-notification-settings',
    SAVE_NOTIFICATION_SETTINGS: 'app:save-notification-settings',
    SEND_NOTIFICATION: 'app:send-notification',
    GET_THEME: 'app:get-theme',
    SAVE_THEME: 'app:save-theme',
  },
} as const;
